# Generated by Django 2.2.1 on 2019-05-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cookbook", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="recipe_time",
            field=models.CharField(
                choices=[("S", "Short"), ("M", "Medium"), ("S", "Long")],
                default="S",
                max_length=1,
            ),
        )
    ]
