# Generated by Django 2.2.1 on 2019-05-07 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cookbook", "0002_recipe_recipe_time")]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="recipe_ingredient",
            field=models.CharField(
                choices=[
                    ("N", "Noodles"),
                    ("R", "Rice"),
                    ("P", "Potatoes"),
                    ("B", "Bulgur"),
                    ("O", "Other"),
                ],
                default="S",
                max_length=1,
            ),
        )
    ]
