# Generated by Django 2.2.1 on 2019-05-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("cookbook", "0003_auto_20190507_1435")]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="recipe_vegetarian",
            field=models.BooleanField(default=False),
        )
    ]
